name: build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov coveralls
      - name: Test pip installation
        run: |
          pip install -e .
      - name: Test with pytest
        run: |
          python -m pytest --cov overhang --cov-report term-missing
      - name: Coveralls
        uses: coverallsapp/github-action@master
        run: coveralls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_SERVICE_NAME: github
